### ISSUE TITLE
Datagate getting "Authentication failed" when connecting to MongoDB

### ISSUE THREAD

**Issue by saloisio** [dizitart/nitrite-database#183]
Hello!

First I'd like to thank you for the great work. I am using nitrite-database without a hitch and it is a wonderful java no-sql db. However when I tried to use the datagate server I'm having less luck. I tried running datagate and mongodb in the following docker-compose.yml configuration:

```
version: '3.7'
      
services:
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: test
      
  datagate:
    image: dizitart/nitrite-datagate
    ports:
      - 8080:8080
      - 9090:9090
    depends_on:
      - db
    environment:
        ## Connection details
        DATAGATE_HOST: 0.0.0.0
        DATAGATE_HTTP_PORT: 8080
        DATAGATE_MONITOR_PORT: 9090
        ## Mongo connection details
        DATAGATE_MONGO_HOST: db
        DATAGATE_MONGO_PORT: 27017
        DATAGATE_MONGO_USER: user
        DATAGATE_MONGO_PASSWORD: password
        DATAGATE_MONGO_DATABASE: test
    command: ["chmod", "+x", "./datagate.sh"]        
    entrypoint: ./datagate.sh
```

When I run `docker-compose up` I'm seeing the database come up properly but datagate is unable to connect to it. The following errors can be seen on the output:

`
db_1        | 2019-08-22T18:16:31.117+0000 I  ACCESS   [conn1] SASL SCRAM-SHA-1 authentication failed for user on test from client 172.18.0.3:33886 ; UserNotFound: Could not find user "user" for db "test"
`

followed soon after by:

`
datagate_1  | Caused by: com.mongodb.MongoCommandException: Command failed with error 18: 'Authentication failed.' on server db:27017. The full response is { "ok" : 0.0, "errmsg" : "Authentication failed.", "code" : 18, "codeName" : "AuthenticationFailed" }
`

I'm not quite sure what is going on as the username and passwords for by the mongo and datagate configurations match in the yml file. Any help would be appreciated.

**Comment by saloisio** [comment]
I just figured out the problem! The MongoDB _MONGO_INITDB_DATABASE_ environment variable simply creates a database with the given name, but it does not automatically give permissions to it. The _MONGO_INITDB_ROOT_USERNAME_ and _MONGO_INITDB_ROOT_PASSWORD_ environment variables create a user that is granted access to a database named "admin". So changing the above docker-compose.yml to the following will work:

```
version: '3.7'
      
services:
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: admin
      
  datagate:
    image: dizitart/nitrite-datagate
    ports:
      - 8080:8080
      - 9090:9090
    depends_on:
      - db
    environment:
        ## Connection details
        DATAGATE_HOST: 0.0.0.0
        DATAGATE_HTTP_PORT: 8080
        DATAGATE_MONITOR_PORT: 9090
        ## Mongo connection details
        DATAGATE_MONGO_HOST: db
        DATAGATE_MONGO_PORT: 27017
        DATAGATE_MONGO_USER: user
        DATAGATE_MONGO_PASSWORD: password
        DATAGATE_MONGO_DATABASE: admin
    command: ["chmod", "+x", "./datagate.sh"]        
    entrypoint: ./datagate.sh
```
